### ISSUE TITLE
cmake libudev ? 

### ISSUE THREAD

**Issue by mk01** [xbianonpi/xbian-sources-libcec#2]
looks like (the imx6) run / cmake configure is not picking up libUDEV-dev 
what (I think) is why it lost its function of autofinding of adapter.

btw nice - was doing some small changes, committed in the morning. xbian master shows very little after its merge. WTF. 
then realised, it was mostly your changes you committed few hours back :) (and git automatically removing patches which results in no change. :)

**Comment by mk01** [comment]
@mkreisl 

ok, no udev... some other #includes were wrong. 
so imx6 working too.

thanks for this initiative !

**Comment by mkreisl** [comment]
Nothing is perfect ...
